# This file was auto-generated by Fern from our API Definition.

import typing

AssociationSpecAssociationCategory = typing.Union[
    typing.Literal["HUBSPOT_DEFINED", "USER_DEFINED", "INTEGRATOR_DEFINED"], typing.Any
]
