# This file was auto-generated by Fern from our API Definition.

import typing

BatchResponseSimplePublicObjectStatus = typing.Union[
    typing.Literal["PENDING", "PROCESSING", "CANCELED", "COMPLETE"], typing.Any
]
