# This file was auto-generated by Fern from our API Definition.

import typing

FilterOperator = typing.Union[
    typing.Literal[
        "EQ",
        "NEQ",
        "LT",
        "LTE",
        "GT",
        "GTE",
        "BETWEEN",
        "IN",
        "NOT_IN",
        "HAS_PROPERTY",
        "NOT_HAS_PROPERTY",
        "CONTAINS_TOKEN",
        "NOT_CONTAINS_TOKEN",
    ],
    typing.Any,
]
