# This file was auto-generated by Fern from our API Definition.

import typing

OauthScope = typing.Union[
    typing.Literal[
        "crm.objects.quotes.write",
        "crm.objects.deals.read",
        "crm.objects.line_items.read",
        "crm.objects.deals.write",
        "crm.objects.quotes.read",
        "crm.objects.line_items.write",
        "crm.objects.companies.read",
        "crm.objects.companies.write",
        "crm.objects.contacts.write",
        "crm.objects.contacts.read",
    ],
    typing.Any,
]
