# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.datetime_utils import serialize_datetime
from ..core.pydantic_utilities import deep_union_pydantic_dicts, pydantic_v1
from .collection_response_associated_id import CollectionResponseAssociatedId
from .value_with_timestamp import ValueWithTimestamp


class SimplePublicObjectWithAssociations(pydantic_v1.BaseModel):
    associations: typing.Optional[typing.Dict[str, CollectionResponseAssociatedId]] = None
    created_at: dt.datetime = pydantic_v1.Field(alias="createdAt")
    archived: typing.Optional[bool] = None
    archived_at: typing.Optional[dt.datetime] = pydantic_v1.Field(alias="archivedAt", default=None)
    properties_with_history: typing.Optional[typing.Dict[str, typing.List[ValueWithTimestamp]]] = pydantic_v1.Field(
        alias="propertiesWithHistory", default=None
    )
    id: str
    properties: typing.Dict[str, typing.Optional[str]]
    updated_at: dt.datetime = pydantic_v1.Field(alias="updatedAt")

    def json(self, **kwargs: typing.Any) -> str:
        kwargs_with_defaults: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        return super().json(**kwargs_with_defaults)

    def dict(self, **kwargs: typing.Any) -> typing.Dict[str, typing.Any]:
        kwargs_with_defaults_exclude_unset: typing.Any = {"by_alias": True, "exclude_unset": True, **kwargs}
        kwargs_with_defaults_exclude_none: typing.Any = {"by_alias": True, "exclude_none": True, **kwargs}

        return deep_union_pydantic_dicts(
            super().dict(**kwargs_with_defaults_exclude_unset), super().dict(**kwargs_with_defaults_exclude_none)
        )

    class Config:
        frozen = True
        smart_union = True
        allow_population_by_field_name = True
        populate_by_name = True
        extra = pydantic_v1.Extra.allow
        json_encoders = {dt.datetime: serialize_datetime}
